name:  CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    name: Unit tests
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5

      - name: Run Tests
        run: mvn -B test


