name:  CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    name: Unit tests
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests
        run: mvn -B test -Dspring.profiles.active=test

  docker:
    needs: tests
    name: Push container to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make jar package and target folder
        run: mvn -B package -Dspring.profiles.active=test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: konstaapeli77/suber:latest
